name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    environment: Prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Package application
        run: mvn clean package

      - name: Synth CloudFormation template
        env:
          PLATFORM_NAME: ${{ vars.PLATFORM_NAME }}
          PLATFORM_HOST: ${{ vars.PLATFORM_HOST }}
          HOSTED_ZONE_ID: ${{ vars.HOSTED_ZONE_ID }}
          CERTIFICATE_ARN: ${{ vars.CERTIFICATE_ARN }}
          ROOT_DB_USER: ${{ secrets.ROOT_DB_USER }}
        run: java -jar target/infra-1.0-SNAPSHOT.jar

      - name: Upload CloudFormation template
        uses: actions/upload-artifact@v4
        with:
          name: cdk-out
          path: cdk.out

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-24.04
    environment: Prod
    steps:
      - name: Download CloudFormation template
        uses: actions/download-artifact@v8
        with:
          name: cdk-out
          path: cdk.out

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy InfraIngress stack
        run: |
          aws cloudformation deploy \
            --stack-name InfraIngress \
            --template-file cdk.out/InfraIngress.template.json

      - name: Deploy InfraCompute stack
        run: |
          aws cloudformation deploy \
            --stack-name InfraCompute \
            --template-file cdk.out/InfraCompute.template.json
